### ISSUE TITLE
Rename the CLI tool (and repo)

### ISSUE THREAD

**Issue by displague** [equinix/metal-cli#101]
Packet is Equinix Metal.

This tool's name should be updated to match.

Here are some alternatives for the CLI command name:
* `metal`
* `equinix metal ...`
* `emctl`

**Comment by displague** [comment]
Added this to the 1.0.0 milestone. We can move this up if we find a good solution prior to that.

Breaking the binary name is a good time to break the argument list and config file structures.
* https://github.com/packethost/packet-cli/issues/111
* https://github.com/packethost/packet-cli/issues/54

**Comment by mrmrcoleman** [comment]
@displague @jmarhee Let's use metal as the name for the CLI moving forwards.

**Comment by displague** [comment]
In preparation for a 1.0 release, I've created a [`metal` branch](https://github.com/packethost/packet-cli/tree/metal).

We can queue up the rename PR and other PRs for [milestone 1.0](https://github.com/packethost/packet-cli/milestone/2).  (We can discuss which issues to add or remove from the milestone if any.)

Once these changes are all in the `metal` branch, we can rename this project to https://github.com/equinix/metal-cli.
