### ISSUE TITLE
Want custom network options exposed (ips and ports)

### ISSUE THREAD

**Issue by bahamat** [equinix/metal-cli#104]
### What problem are you facing?

We want to provision servers with custom networking configuration, without making a trip to the web site. Currently, after I provision a server I need to open the web page and define the correct networking for it with custom vlans that we've already created.

### How could the Equinix Metal CLI help solve this problem?

Allow defining specific network configuration from the cli, both in `server create` and `server update` subcommands.

**Comment by displague** [comment]
I think this request comes down to adding support for the `ip_addresses` field ( https://github.com/packethost/packngo/blob/master/devices.go#L295) in device create requests.

I would also like to see the CLI pick up support for working with VLAN attachment and network port bonding:
https://github.com/packethost/packngo/blob/a38fa6e7155670401c2b7843747036ffc1ed50b4/ports.go#L13-L26

**Comment by bahamat** [comment]
No, it's not just the IP field. I'm creating multiple custom vlans and I want to individually assign which nics get which vlans. Looking at the json output from `packet server get -i <id>`, I want to control `network_ports` at provision time.

**Comment by bahamat** [comment]
To clarify, I need both `ip_address` and `network_ports`.

**Comment by displague** [comment]
Anoither set of network options that should be exposed is `port` options, to enable network type conversion (includes bonding and vlan attachment).

**Comment by displague** [comment]
Here's what I'm thinking:
```sh
metal port get --id [id]
metal port bond --id [id] --bulk
metal port disbond --id [id] --bulk
metal port assign --id [id] --vxlan [vxlan] --native [native] # true can be set to assign native
metal port assign --id [id] --vxlan [vxlan] --native [native] # false can be set to unassign native
metal port unassign --id [id] --vxlan [vxlan]
metal port layer2 --id [id] --force # force skips the prompt to remove (and lose) existing address assignments
metal port layer3 --id [id] --public-ipv4 --public-ipv6 # private ipv4 is required for layer3
metal port layer3 --id [id] --reservation-id [reservation-id] # if this is supported, especially if multiple are accepted
```

`-i [id]` could be substituted for `-d [device_id] -p [port_name]`
`--vxlan [vxlan]` could be substituted for `--vlan-id [vlan_uuid]`
`--ip-reservation-id [ip_reservation_id]` could be substituted for `--address [address]`

Assignments would use the Bulk VLAN Assignment API methods.
Bulk VLAN Assignment requests and batches would not necessarily be made visible through the API.

---

https://metal.equinix.com/developers/docs/layer2-networking/overview/
https://metal.equinix.com/developers/docs/layer2-networking/vlans/
https://metal.equinix.com/developers/docs/layer2-networking/native-vlan/

---

I did start some work towards this when this was `packet-cli`. I didn't get very far and much has changed since then.

https://github.com/equinix/metal-cli/compare/main...displague:ports?expand=1

**Comment by displague** [comment]
@bahamat
> I want to control network_ports at provision time

The best place to show your interest in that is here: https://metal.canny.io/servers-and-configs/p/restrict-org-from-public-internet-access

**Comment by displague** [comment]
For IP Address assignments at device creation, it is not possible to boot into Layer2 mode directly today. We could chase the Device Create with a Convert to Layer2 request, but this could also be done by exposing the CLI commands above and letting the user do the same.

I think reasonable `metal device create` arguments for interacting with the `ip_addresses` API field would be:
`--public-ipv4=false` `--public-ipv6=false` (these default to `true` in the API).

For additional addresses:
`--address [address]` or `--ip-reservation-id [ip_reservation_id]` (this has naming parity with `--hardware-reservation-id`)

In the event that Layer2 booting became available, I'd like for the CLI arguments to match the API request structure. While that's not defined today, I imagine that could look like `--private-ipv4=false` (sent with all of the other "false" settings).

**Comment by displague** [comment]
I'm considering the following, but I think it becomes too complex:

```
metal port convert --id [port_id] {--bond=[bond:*bool]} {--bulk} {--layer2=[layer2:*bool} {--force} {--public-ipv4} {--public-ipv6} {--ip-reservation-id}
```

**Comment by displague** [comment]
Likewise, I am considering how we could combine the `assign` and `unassign` commands into a single `metal port vlan`:

```
metal port vlans --id [port_id] --assign=[vxlan|vlan_uuid] --assign=[vxlan|vlan_uuid] --assign=[vxlan|vlan_uuid][,native]
metal port vlans --id [port_id] --unassign=[vxlan|vlan_uuid] 
```
This format would take great advantage of the bulk VLAN assignment API endpoints.

**Comment by displague** [comment]
@cprivitere suggests something more like this to avoid the comma syntax:
```
metal port vlans --id [port_id] --native=[vxlan]
```

This would be effectively a `--assign` with native flags.
