### ISSUE TITLE
hardware-reservation returning incomplete list

### ISSUE THREAD

**Issue by dsieczko** [equinix/metal-cli#116]
### What happened?

`p hardware-reservation get -p <id>` only returning 6 reservations in a project with more than 6 reservations.

Version 0.4.0

**Comment by t0mk** [comment]
@displague @dsieczko 
Hard to debug just looking at the code without having a project with more than the 6 reservations. I can debug it if you give me access to such project.

If that's too much of a problem, it might help if you can ask the customer to run 
`PACKNGO_DEBUG=1 packet-cli hardware-reservation get -p $PROJECT_ID &> logg`
.. and then upload the log. There we might see what the API is returning.

The command will make the tool print also HTTP traffic and will redirect both stdin and stderr to the log file. Don't worry about the auth token, it's redacted (but it's always good to check before sharing).

**Comment by displague** [comment]
@dsieczko this should have been fixed in v0.5.0. 
Please reopen this if the problem persists.
