### ISSUE TITLE
packet-cli should obey XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by grahamc** [equinix/metal-cli#12]
Right now Packet by default stores configuration in `~/.packet/config`. The XDG spec says:

>  $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

It isn't a huge, but this is considered to be less than ideal behavior these days. Also, I happen to know at least one person whose ~/ is a tmpfs, but XDG_CONFIG_HOME points to a persistent storage, and thusly any configuration files which are written to ~ are deleted on each reboot. This person isn't me.

I appreciate that the cli accepts a key and config file via options.

**Comment by Mic92** [comment]
alternatively one can also configure all aspects via environment variables https://github.com/packethost/packet-cli/blob/39670984097f782454dcffe2dbac7756772d3449/cmd/root.go#L87

**Comment by jasmingacic** [comment]
You can also use:
```
 --config string   Path to JSON or YAML configuration file
```
I will close this as non issue.

**Comment by grahamc** [comment]
I know I could, but it is still a bit of an issue to not follow XDG.
