### ISSUE TITLE
allow users to specify projects, devices by name instead of ID

### ISSUE THREAD

**Issue by alexeldeib** [equinix/metal-cli#15]
This is a quality of life/ergonomics improvement for developers. Passing GUIDs is generally not fun or easy from a human standpoint. People generally prefer working with recognizable, memorable strings. 

I propose we hide this complexity from users. If the input provided by the user looks like a GUID, CLI should attempt to use it as such. If the input is otherwise a freeform string, the CLI should perform the necessary backend calls to correlate the name to the given project/device in the user account, and still return the correct result (as opposed to 404 in current behavior).

Happy to PR, wanted to open an issue to discuss if this is desirable first.

**Comment by jasmingacic** [comment]
I believe this has been partially solved by #19.
I will close it for now if there is a need we can revisit this.
