### ISSUE TITLE
tests are not run

### ISSUE THREAD

**Issue by displague** [equinix/metal-cli#151]
#150 revealed that a few things were missed in the renaming and file moving from packet to metal. 

The tests will have to be moved from tests/ to their relevant path, for example.  I'll admit I wasn't overly concerned with the tests as many of these are E2E and that seems like overkill for this CLI.

I think we should be testing that mocked responses are handled in an intended way.

This issue is to track the movement (or deeper changes) to the tests.

Part of #123

**Comment by displague** [comment]
Go tests are now run which today ensures minimally that the CLI cmd can be constructed and the command can be built.

**Comment by ctreatma** [comment]
We have started building out an e2e test suite as part of the migration off of packngo, and we regularly run that suite in CI.  Closing this issue; if there are things we want to change about the new e2e tests, we can add new issues for that.
