### ISSUE TITLE
CLI does not exit with an error in certain cases

### ISSUE THREAD

**Issue by jmarhee** [equinix/metal-cli#24]
I am using the packet CLI in a test, for example:

https://github.com/packet-labs/packet-multiarch-k8s-terraform/blob/master/.drone.yml#L68

where I am creating, and then attempting to delete a keypair. The way I'm identifying the key ID isn't happening correctly, so this last step _should_ (because it's a bad/malformed argument value) be failing, but seems to exit silently (and exits `0` or else the test would fail, which it hasn't). So the argument format matches, but doesn't give a valid value for that argument, in this case. 

This is easy enough to handle on my end, but the output for most of these operations seems to exit silently if it doesn't trigger the help prompts, so I figured it was worth reporting.

**Comment by jasmingacic** [comment]
@jmarhee can you send example of the command in question?

**Comment by jacobsmith928** [comment]
@jmarhee ping ^^

**Comment by jmarhee** [comment]
The use case in the example above was adding an SSH key (which it would do), and then removing it:

```
packet ssh-key delete -i $KEY_UUID
```
and if it did not find a key, or else returned an error, it would still exit successfully (rather than surfacing the API error response as an unsuccessful operation with the cli)

**Comment by jasmingacic** [comment]
@jmarhee 

This is how it behaves for me:
```
$ export KEY_UUID=blah
$ packet ssh-key delete -i $KEY_UUID
✔ Are you sure you want to delete project : : y
Client error: DELETE https://api.packet.net/ssh-keys/blah: 404 Not found 
```
in case the environment variable `KEY_UUID` is not set the command assumes you didn't pass the parameter and returns help message

```
$ unset KEY_UUID
$ packet ssh-key delete -i $KEY_UUID
Error: flag needs an argument: 'i' in -i
Usage:
  packet ssh-key delete [flags]

Flags:
  -f, --force       Force removal of the SSH key
  -h, --help        help for delete
  -i, --id string   UUID of the SSH key

Global Flags:
      --config string   Path to JSON or YAML configuration file
```
You should surround  the environment variable with double quotes like this:
```
$ packet ssh-key delete -i "$KEY_UUID" -f 
Client error: DELETE https://api.packet.net/ssh-keys/: 404 Not found 
```
Does this help?

**Comment by jmarhee** [comment]
I don't recall if I tried this or not, but if the above yields the correct erroring exit code, then I'm fine calling this matter resolved. Thanks!

**Comment by jacobsmith928** [comment]
@jasmingacic want to close it out por favor?
