### ISSUE TITLE
.dms darwin binary

### ISSUE THREAD

**Issue by interregna** [equinix/metal-cli#25]
Binary file for maOS: packet-darwin-amd64 binary links to a .dms file which does not appear to be a valid installable binary

**Comment by jasmingacic** [comment]
The binary is not installable like a DMG package but you are supposed to do the following https://github.com/packethost/packet-cli#mac-os-x 
Can you please give it a try?

**Comment by interregna** [comment]
Thanks. This looks like a Safari download handling issue for files with no extensions. https://forums.macrumors.com/threads/safari-erroneously-adding-dms-extension-to-downloads.2080108/ 

Perhaps add extensions to the compiled binary files?

I was able to make this work by renaming to packet.sh and changing permissions to executable chmod +x .

**Comment by jasmingacic** [comment]
Renaming the binary to `packet.sh` shouldn't do anything. Only doing `chmod +x` should do it.

**Comment by interregna** [comment]
yes, I agree.
