### ISSUE TITLE
suggestion: load default project id from config file

### ISSUE THREAD

**Issue by colemickens** [equinix/metal-cli#30]
Suggestion:

While I greatly appreciate the global `--project-id` flag, It would be nice if we could have a default project id specified in the config file as well.

**Comment by jasmingacic** [comment]
It would be practical indeed but there is a problem with current implementation.

Commands like `packet device get` accept either project-id or device id.
So if we would do something like this:
```
PACKET_PROJECT_ID=93125c2a-8b78-4d4f-a3c4-7367d6b7cca8 go run main.go device get -i 5bca09f0-0f91-491b-987f-151786d5cb00
```
it would error with this:
```
Either id or project-id can be set.
```

It wouldn't be a simple fix.

Do you have any suggestions?

**Comment by colemickens** [comment]
Aha, interesting. No good suggestions from me, I didn't realize the CLI/API could be used this way. For now there's no real issue setting project id. It's certainly much preferred to the opposite, where it would overly-rely on global state. Thanks!

**Comment by displague** [comment]
More discussion on this in #54
