### ISSUE TITLE
--termination-time rejects values that the API accepts

### ISSUE THREAD

**Issue by colemickens** [equinix/metal-cli#31]
As I'm trying to adopt `packet-cli` over my pile of shell scripts, I've noticed that the termination_time I was calculating and passing directly to the API is rejected by the CLI. This seems unfortunate, to me.

It would be nice if the same values could be passed to the CLI. Better yet, if you could pass things like `--termination-time="+2 hours"` would be very cool as well, since this is what I'm doing anyway:

```bash
# should work, but doesn't:
termtime="$(TZ=UTC date --date="2 hour" --iso-8601=seconds)"
packet device create --termination-time="${termtime}" ...

# maybe in the future?
packet device create --termination-time="+2 hours"
```

**Comment by colemickens** [comment]
ref: https://support.packet.com/kb/articles/spot-market

**Comment by colemickens** [comment]
It's an easy fix, but it makes me question what was the original thinking...

```diff
-			parsedTime, err := time.Parse(`"` + time.RFC3339 + `"`, terminationTime)
+			parsedTime, err := time.Parse(time.RFC3339, terminationTime)
```

**Comment by jasmingacic** [comment]
Feel free to submit the fix.

**Comment by colemickens** [comment]
Thanks @jasmingacic for dealing with this and the other issues I opened, sorry I didn't get around to submitting this one!
