### ISSUE TITLE
Project structure, globals

### ISSUE THREAD

**Issue by rusenask** [equinix/metal-cli#35]
Usually Go applications use `cmd` directory in a bit different way. It should probably be `cmd/packet-cli` or just `cmd/packet` to get a good executable name. 

Also, since everything is mashed together in a single directory, there's already a problem defining any new variables due to globals like https://github.com/packethost/packet-cli/blob/master/cmd/create_device.go#L31-L51. 

It might make sense to remove those globals and those init functions https://github.com/packethost/packet-cli/blob/master/cmd/create_device.go#L128-L154

**Comment by jasmingacic** [comment]
This is duplicate of #33 so we can move the conversation there.
