### ISSUE TITLE
Install via brew?

### ISSUE THREAD

**Issue by deitch** [equinix/metal-cli#38]
Can we make the packet cli available on Mac (and Linux) via [homebrew](https://brew.sh)? Also might want to think about Windows, where you can install via homebrew using WSL, or possibly [Chocolatey](https://chocolatey.org).

**Comment by jacobsmith928** [comment]
@jasmingacic thoughts?

**Comment by jasmingacic** [comment]
It is doable, but before we'd have to set up a CI/CD pipeline so we can ensure that what we have is tested regularly.

**Comment by jacobsmith928** [comment]
Fully supportive of a CI/CD pipeline, could you coordinate with @deitch to align with what he has done for CCM and CSI?

**Comment by jasmingacic** [comment]
Hey @deitch should we get together and go over what @jacobsmith928 suggested?

**Comment by deitch** [comment]
Sounds good @jasmingacic . I am going to open a new issue just for CI, so we can keep the discussion focused and leave this one for brew.

**Comment by displague** [comment]
Now that goreleaser is being used on each tagged release through GitHub Workflows, this is more attainable:
https://goreleaser.com/customization/homebrew/

**Comment by idvoretskyi** [comment]
Any updates on this? :)

**Comment by displague** [comment]
@idvoretskyi I created a brew tap, but I'll need to verify that this configuration works first.
https://github.com/equinix/homebrew-tap/pull/1

The next step would be to update goreleaser in this project to update the tap on each release.

**Comment by crayzeigh** [comment]
Created a PR that should cause goreleaser to generate the brew formula into [equinix/homebrew-tap](https://github.com/equinix/homebrew-tap) on each release once committed that should at least solve the bare minimum requirements. Probably worth thinking about committing and maintaining in homebrew-core after we confirm this is working.

**Comment by displague** [comment]
I've created an issue to track a limitation that I encountered when setting up the secrets needed to publish to the tap.

In the meanwhile, I can grant the tap account access to metal-cli so that one token can update both projects.

**Comment by displague** [comment]
Noting here that it is also possible to install on FreeBSD via https://www.freshports.org/sysutils/equinix-metal-cli/ as noted in the README.md thanks to https://github.com/equinix/metal-cli/pull/249
