### ISSUE TITLE
performance of "packet-cli project get"

### ISSUE THREAD

**Issue by vielmetti** [equinix/metal-cli#51]
My account has a lot of projects (about 90). 

When I ran `packet-cli project get` today, this took 1m18s to the first output. In fact I wasn't sure that it it was working at all and after about 15s I interrupted the output.

**Comment by displague** [comment]
I experienced the same thing and was wondering if it could be possible to filter by the organization id.

**Comment by displague** [comment]
Some potential sources of poor timing to investigate:

* upstream API (single response timing vs multiple request timing (rate-limiting?))
* pagination (is this is the only form of data processing?)
* lack of filtering (request less from the API)
