### ISSUE TITLE
Document `go get` install method

### ISSUE THREAD

**Issue by displague** [equinix/metal-cli#53]
## What problem are you facing?

Installing the Packet CLI by downloading a binary from Github is mildly cumbersome. The binary must then be `chmod`'d and moved into the correct directory.  Binaries are available for many operating systems, but there are always others.

While tools such as brew (#38) can make this experience easier, this is a Go project. Go already has excellent support for installing tools through a common interface:

The following works today, given certain requirements such as go version.

```bash
GO111MODULE=on go get github.com/packethost/packet-cli
``` 
##  How can packet-cli help?

Instructions should be provided at https://github.com/packethost/packet-cli/blob/master/README.md#installation for installing using this generic approach.

**Comment by displague** [comment]
Unrelated, but whoever takes this on should correct the typo of "Daby" in the README.md, which should be "by".

**Comment by nanaboat** [comment]
I will like to work on this @displague @rawkode.

**Comment by rawkode** [comment]
Let me know if you need any help, @nanaboat

**Comment by nanaboat** [comment]
@displague I could not find the typo "Daby" in the README.md

**Comment by displague** [comment]
The typo was corrected in an unrelated pr after this issue was created.

**Comment by nanaboat** [comment]
@displague @rawkode I have a PR for this issue. [](https://github.com/packethost/packet-cli/pull/91)

**Comment by displague** [comment]
Closed by #95
