### ISSUE TITLE
Support for plurals

### ISSUE THREAD

**Issue by gianarb** [equinix/metal-cli#98]
### What problem are you facing?

I never get the right command at first. Because I use `projects`, or `devices` and not `project` and `device`

### How could the Equinix Metal CLI help solve this problem?

should we add support for plurals?

**Comment by gianarb** [comment]
Probably I am using an old version! Thanks @displague !https://github.com/packethost/packet-cli/pull/60

**Comment by displague** [comment]
I'm also interested in aliases for `get` and `list`, I can never remember which tool uses which verb.

**Comment by displague** [comment]
And wouldn't it be nice if `packet get devices` worked too? If param[1] is one of the common actions (get,list,delete,update,create), would it be crazy to just swap the two parameters?

What if someone said `packet get <tab><tab>` should it know that there are X resources that support `get` and offer the names of those as help? Maybe.

**Comment by displague** [comment]
`packet ssh-keys` should be added. I just ran into that one.
